language: node_js
node_js:
  - "10"

cache: yarn

before_install:
  - echo ${FAKE_NPM_TOKEN}
  - echo "//registry.npmjs.org/:_authToken=${FAKE_NPM_TOKEN}" > .npmrc

# Run the the validate script
install:
  - yarn global add bolt
  - echo bolt

script:
  - echo bolt build
  - echo bolt test

deploy:
  skip_cleanup: true
  provider: script
  script: cat .npmrc && bolt publish
  on:
    publish-branch
